"""empty message

Revision ID: 6fde0194d675
Revises: e83f06a9655c
Create Date: 2020-08-21 17:05:15.183345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fde0194d675'
down_revision = 'e83f06a9655c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('site',
    sa.Column('site_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('url', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('site_id'),
    sa.UniqueConstraint('url')
    )
    op.add_column('hotel', sa.Column('site_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'hotel', 'site', ['site_id'], ['site_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'hotel', type_='foreignkey')
    op.drop_column('hotel', 'site_id')
    op.drop_table('site')
    # ### end Alembic commands ###
