"""empty message

Revision ID: 857b780b881e
Revises: 6fde0194d675
Create Date: 2020-10-11 20:18:36.271133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '857b780b881e'
down_revision = '6fde0194d675'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('hotel', 'diaria',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)
    op.alter_column('hotel', 'estrelas',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=1),
               existing_nullable=False)
    op.alter_column('hotel', 'site_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('hotel', 'site_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('hotel', 'estrelas',
               existing_type=sa.Float(precision=1),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('hotel', 'diaria',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)
    # ### end Alembic commands ###
